# Generated by Django 5.2.3 on 2025-07-06 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="commentreply",
            name="comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="voice_note",
            field=models.FileField(blank=True, null=True, upload_to="comments/audio/"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="feed.post",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
