# Generated by Django 5.2.3 on 2025-07-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_comment_audio_reply_commentreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
    ]
