# Generated by Django 5.2.3 on 2025-07-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0006_postbookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/images/"),
        ),
        migrations.AddField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
