# Generated by Django 5.2.3 on 2025-07-07 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_post_image_post_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bg_color",
            field=models.CharField(default="brown", max_length=20),
        ),
        migrations.AddField(
            model_name="post",
            name="font_style",
            field=models.CharField(default="serif", max_length=30),
        ),
        migrations.AddField(
            model_name="post",
            name="text_color",
            field=models.CharField(default="black", max_length=20),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("glimpse", "Glimpse"),
                    ("pose_battle", "Pose Battle"),
                    ("article", "Article"),
                    ("poll", "poll"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ArticlePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("font", models.CharField(default="Roboto", max_length=50)),
                ("font_size", models.IntegerField(default=16)),
                ("text_color", models.CharField(default="#000", max_length=10)),
                (
                    "background_color",
                    models.CharField(default="#f4e6d5", max_length=10),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article",
                        to="feed.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=100)),
                ("votes", models.PositiveIntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_options",
                        to="feed.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoseBattleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenger_media",
                    models.FileField(upload_to="pose_battles/challenger/"),
                ),
                (
                    "opponent_media",
                    models.FileField(
                        blank=True, null=True, upload_to="pose_battles/opponent/"
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                ("accepted", models.BooleanField(default=False)),
                ("denied", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pose_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pose_opponents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pose_battle_entry",
                        to="feed.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("saves", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("reach_score", models.FloatField(default=0.0)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="feed.post",
                    ),
                ),
            ],
        ),
    ]
