# Generated by Django 5.2.3 on 2025-07-07 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0008_post_bg_color_post_font_style_post_text_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="posebattleentry",
            old_name="expires_at",
            new_name="ended_at",
        ),
        migrations.AddField(
            model_name="posebattleentry",
            name="challenger_votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="posebattleentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="posebattleentry",
            name="opponent_votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="posebattleentry",
            name="voted_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="pose_battle_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="posebattleentry",
            name="opponent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pose_challenges_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="posebattleentry",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pose_battle",
                to="feed.post",
            ),
        ),
        migrations.AlterField(
            model_name="posebattleentry",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
