# Generated by Django 5.2.3 on 2025-07-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0009_rename_expires_at_posebattleentry_ended_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="saves_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="shares_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
