# Generated by Django 5.2.3 on 2025-07-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileengine', '0003_profile_allowed_viewers_profile_display_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
